# Dependencies
markdown:         kramdown
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Funding Mission Schools
tagline:          ''
description:      ''
url:              https://github.com/alex-mayfield
baseurl:          /fmsreport

author:
  name:           ''
  url:            

paginate:         2

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/alex-mayfield/fmsreport/
